# -------- Build stage --------
FROM node:20-alpine AS builder
WORKDIR /app

# Copy local frontend code
COPY hospital-frontend/ ./

# Install deps and build
RUN npm install
RUN npm run build

# -------- Run stage --------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY docker-git-fullstackapp/nginx.conf /etc/nginx/conf.d/default.conf
# Copy built files from builder
COPY --from=builder /app/dist ./

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
